# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/forsh/Desktop/Everything/Vivado Labs/Lab_5_152_B3 - Attempt 2/Lab_5_152_B3/Lab_5_152_B3.srcs/sources_1/bd/Game_Design/ip/Game_Design_ilmb_bram_if_cntlr_0/Game_Design_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'Game_Design_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/forsh/Desktop/Everything/Vivado Labs/Lab_5_152_B3 - Attempt 2/Lab_5_152_B3/Lab_5_152_B3.srcs/sources_1/bd/Game_Design/ip/Game_Design_ilmb_bram_if_cntlr_0/Game_Design_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Game_Design_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/forsh/Desktop/Everything/Vivado Labs/Lab_5_152_B3 - Attempt 2/Lab_5_152_B3/Lab_5_152_B3.srcs/sources_1/bd/Game_Design/ip/Game_Design_ilmb_bram_if_cntlr_0/Game_Design_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'Game_Design_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/forsh/Desktop/Everything/Vivado Labs/Lab_5_152_B3 - Attempt 2/Lab_5_152_B3/Lab_5_152_B3.srcs/sources_1/bd/Game_Design/ip/Game_Design_ilmb_bram_if_cntlr_0/Game_Design_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Game_Design_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
